### PR TITLE
Use datetime.date to represent dates more efficiently

### PR DESCRIPTION
**Pull request by sbrugman**

### CODE REVIEW

**Comment by ieaves** [comment]
Since pandas internally maps datetime objects into Timestamp[ns] (for valid timestamp ranges) and there is no Timestamp analogue to a datetime.date we can't rely on `is_datetime64_any_dtype` to perform this check. You can verify for yourself that

```
s = pd.Series([datetime.date(2020, 1, 1)])
pdt.is_datetime64_any_dtype(s)
>>> False
```

If you want to define Date as a sequence of datetime.date objects you'll need to create an identity relation from Generic and create an InferenceRelation from DateTime. Users coercing a time series sequence to visions Date types will also lose access to the `.dt` accessor.

**Comment by sbrugman** [comment]
Given that pandas internally maps datetimes to pd.Timestamp[ns], the Date and Time type implementations will diverge from Datetime in this specific case. We can leverage the new `isinstance_attrs` method. Added class name checking functionality for dealing with [`isinstance(datetime.datetime(), datetime.date)` returning True](https://stackoverflow.com/a/53495621/470433).

This PR is also blocked by #75.

**Comment by sbrugman** [comment]
Note that series of `datetime.date` and `datetime.time` are now recognized as types, but a series of `datetime.datetime` is not. The first two come from the the pandas datetime accessor (`.dt.date` and `.dt.time`). It might make sense to add a second Datetime type using `datetime.datetime` as well.

**Comment by ieaves** [comment]
LGTM

**Pull request merged**
