### PR TITLE
[WIP] Extends series coverage

### PR DESCRIPTION
**Pull request by sbrugman**

### CODE REVIEW

**Comment by ieaves** [comment]
@sbrugman everything is fixed. You should particularly review the changes to float before merging.

**Comment by sbrugman** [comment]
I've added two test cases that are false negatives in the current implementation. The leading zero's relationship test needs more sophistication.

**Comment by ieaves** [comment]
What does that even mean? If you have ideas please feel free to modify the test.

**Comment by sbrugman** [comment]
LGTM

**Pull request merged**
